name: ChestRestock
main: com.dumptruckman.chestrestock.ChestRestockPlugin
version: maven-version-number
author: dumptruckman

commands:
  cr:
    description: Views/sets/changes the settings of the chest you are targetting.
    usage: /<command>