name: ChestRestock
main: com.dumptruckman.chestrestock.ChestRestock
version: 1.1
author: dumptruckman

commands:
  chestrestock:
    description: Views/sets/changes the settings of the chest you are targetting.
    usage: |
           /<command> <subcommand>
           Subcommands: help, check, set, period, update, periodmode, 
           restockmode, preserveslots, indestructible, disable, reload,
           playerlimit, restock, name
    aliases: cr